server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:postgresql://postgresql:5432/auth_service"
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  application:
    name: identity-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signKey: "Ntshn69BGsgBsLUhuqmTg9LI+YNKRzvzSz9BUVpLqpvEpCz4AbNqkx4Xk2HejaPM"
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html